source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'HHYYModelStudy' do
    
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'YYModel'

end
