source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'HHSDWebImageStudy' do

#pod 'SDWebImage', '3.7.6'

pod 'SDWebImage', '4.4.2'
pod 'SDWebImage/WebP'
pod 'SDWebImage/GIF'
pod 'SDWebImage/MapKit'

end
