source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'HHMLeaksFinderStudy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'MLeaksFinder' '1.0.0' # 并自动导入了 FBRetainCycleDetector (0.1.4)

end
